//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechTelop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFileTextBoxText {
            get {
                return ((string)(this["OutputFileTextBoxText"]));
            }
            set {
                this["OutputFileTextBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubscriptionKeyTextBoxText {
            get {
                return ((string)(this["SubscriptionKeyTextBoxText"]));
            }
            set {
                this["SubscriptionKeyTextBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSubscriptionKeyCheckBoxChecked {
            get {
                return ((bool)(this["ShowSubscriptionKeyCheckBoxChecked"]));
            }
            set {
                this["ShowSubscriptionKeyCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ToLanguageComboBoxSelectedIndex {
            get {
                return ((int)(this["ToLanguageComboBoxSelectedIndex"]));
            }
            set {
                this["ToLanguageComboBoxSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int FromLanguageComboBoxSelectedIndex {
            get {
                return ((int)(this["FromLanguageComboBoxSelectedIndex"]));
            }
            set {
                this["FromLanguageComboBoxSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Point SpeechTelopLocation {
            get {
                return ((global::System.Drawing.Point)(this["SpeechTelopLocation"]));
            }
            set {
                this["SpeechTelopLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HotKeyComboBoxSelectedIndex {
            get {
                return ((int)(this["HotKeyComboBoxSelectedIndex"]));
            }
            set {
                this["HotKeyComboBoxSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddShiftKeyCheckBox {
            get {
                return ((bool)(this["AddShiftKeyCheckBox"]));
            }
            set {
                this["AddShiftKeyCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddCtrlKeyCheckBox {
            get {
                return ((bool)(this["AddCtrlKeyCheckBox"]));
            }
            set {
                this["AddCtrlKeyCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddAltKeyCheckBox {
            get {
                return ((bool)(this["AddAltKeyCheckBox"]));
            }
            set {
                this["AddAltKeyCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string HideAfterSecondsMaskedTextBoxText {
            get {
                return ((string)(this["HideAfterSecondsMaskedTextBoxText"]));
            }
            set {
                this["HideAfterSecondsMaskedTextBoxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ServiceRegionComboBoxSelectedIndex {
            get {
                return ((int)(this["ServiceRegionComboBoxSelectedIndex"]));
            }
            set {
                this["ServiceRegionComboBoxSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTextToSpeechCheckBoxChecked {
            get {
                return ((bool)(this["EnableTextToSpeechCheckBoxChecked"]));
            }
            set {
                this["EnableTextToSpeechCheckBoxChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VoiceNameComboBoxSelectedIndex {
            get {
                return ((int)(this["VoiceNameComboBoxSelectedIndex"]));
            }
            set {
                this["VoiceNameComboBoxSelectedIndex"] = value;
            }
        }
    }
}
